name: Publish jdkx
run-name: Publish ${{ github.event.inputs.pkg_version  }}
on:
  workflow_dispatch:
    inputs:
      pkg_version:
        description: 'set the publish version'
        type: string
        required: false
        default: '2.0.1.0-jdk8-SNAPSHOT'
      jdk_version:
        description: 'set the jdk version'
        type: int
        required: false
        default: 8

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
#      with:
#        ref: jdk8
        
    - name: Set up JDK ${{ github.event.inputs.jdk_version  }}
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ github.event.inputs.jdk_version  }}
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE


    - name: change version to ${{ github.event.inputs.pkg_version  }}
      run: |        
        mvn versions:set -DnewVersion=${{ github.event.inputs.pkg_version  }}
        ls *.xml*
        

    - name: change compile version to 1.8
      if: ${{ github.event.inputs.jdk_version <= 8 }}
      run: |
        sed -i.bak 's|<maven\.compiler\.target>[^<]*</maven\.compiler\.target>|<maven.compiler.target>1.8</maven.compiler.target>|g' pom.xml

    - name: change compile version to ${{ github.event.inputs.jdk_version }}
      if: ${{ github.event.inputs.jdk_version > 8 }}
      run: |
        sed -i.bak 's|<maven\.compiler\.target>[^<]*</maven\.compiler\.target>|<maven.compiler.target>${{ github.event.inputs.jdk_version }}</maven.compiler.target>|g' pom.xml
    

    - name: debug build
      run: |
        head -c 800 pom.xml
        mvn test

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to the Maven Central Repository
      run: |
#       has a "performRelease" profile in pom.xml, only use gpg when -DperformRelease=true
        mvn -DperformRelease=true -Dmaven.test.skip --batch-mode clean deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
