name: Publish main(jdk11)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 11
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE


    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to the Maven Central Repository
      run: |
        mvn --batch-mode clean deploy
        mvn nexus-staging:release
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
