name: Publish main(jdk11)

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 11
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: change version to jdk11
      run: |
        pwd
        ls
        sed -i 's/-jdk8<\/version>/-jdk11<\/version>/g' pom.xml
        sed -i 's/-jdk8-SNAPSHOT<\/version>/-jdk11-SNAPSHOT<\/version>/g' pom.xml
        ls *.xml*
        head -c 500 pom.xml
        mvn -N versions:update-child-modules

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to the Maven Central Repository
      run: |
        mvn --no-transfer-progress --batch-mode clean deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
