name: Publish jdk11

on:
  workflow_dispatch:
    inputs:
      pkg_version:
        description: 'set the publish version'
        type: string
        required: false
        default: '2.0.0.0-jdk11-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 11
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: change version to jdk11
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.pkg_version  }}
        ls *.xml*
        head -c 500 pom.xml

    - name: debug build
      run: |
        mvn -pl nlp-ext -am test

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to the Maven Central Repository
      run: |
        mvn --no-transfer-progress --batch-mode clean deploy -Dmaven.test.skip=true
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
