name: test-maven

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: jdk8
        
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: 8
        cache: 'maven'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE


    - name: Build with Maven
      run: |
        ls ~/.m2
        cat ~/.m2/settings.xml
